export const LOGIN_DIALOG_VISIBLE = 'LOGIN_DIALOG_VISIBLE'
export const REGISTRATION_DIALOG_VISIBLE = 'REGISTRATION_DIALOG_VISIBLE'
export const SET_FETCH_STATUS = 'SET_FETCH_STATUS'
export const SET_RESPONSE_MESSAGE ='SET_RESPONSE_MESSAGE'