export const CHANGE_POKEMON_TYPE_FILTER = 'CHANGE_POKEMON_TYPE_FILTER'
export const SEARCH_POKEMON_BY_NAME = 'SEARCH_POKEMON_BY_NAME'
export const ADD_POKEMON_TO_FAVORITE_BY_ID = 'ADD_POKEMON_TO_FAVORITE_BY_ID'
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER'
export const CHANGE_ITEMS_AMOUNT_PER_PAGE = 'CHANGE_ITEMS_AMOUNT_PER_PAGE'

export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST'
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS'
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE'

export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'
export const SUGGEST_SPINNER_VISIBLE = 'SUGGEST_SPINNER_VISIBLE'
